manifest:
  remotes:
    - name: myzmk
      url-base: https://github.com/dac63701
  projects:
    - name: zmk
      remote: myzmk
      revision: main
      import: app/west.yml
  self:
    path: config